# Generated by Django 3.2.7 on 2021-11-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_token_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(max_length=40),
        ),
    ]
