# Generated by Django 3.2.7 on 2021-10-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_alter_item_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_in_list_constraint',
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('list', 'text')},
        ),
    ]
