# Generated by Django 3.2.7 on 2021-10-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_auto_20211025_1120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('text', 'list'), name='unique_item_in_list_constraint'),
        ),
    ]
